import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.problem': 'Problem',
    'nav.clinical': 'Clinical Insight',
    'nav.solution': 'Solution',
    'nav.how-it-works': 'How It Works',
    'nav.dashboard': 'Kinematics Data',
    'nav.muscle': 'Muscle Activation',
    'nav.summary': 'Dashboard',
    // Home
    'home.title': 'Groundwork',
    'home.subtitle': 'Catches equipment failures before they happen. Proves it never left the plant.',
    // Problem
    'problem.title': 'The Problem',
    'problem.text': 'A pentest finds your vulnerabilities... but it costs',
    'problem.cost': '$50,000',
    'problem.stat1.number': '45%',
    'problem.stat1.text': 'Of discovered vulnerabilities remain unpatched after 12 months because fixing them requires manual effort nobody has time for.',
    'problem.stat2.number': '$4.4M',
    'problem.stat2.text': 'Average cost of a data breach in 2025, with vulnerability exploitation remaining one of the leading causes.',
    'problem.stat3.number': '17hrs',
    'problem.stat3.text': 'Per week developers spend on security tasks, much of it translating reports into fixes that could have been automated.',
    'problem.question': 'How do we give every developer, not just enterprises, automated security testing that goes all the way to the fix?',
    // Clinical
    'clinical.title': 'Clinical Insight',
    'clinical.text1': 'Peak Torque (PT) and Time-to-Peak Torque (TPT) are recognized as critical markers of full ACL recovery, especially the symmetry between the injured and healthy knee (Westwood et al., 2025).',
    'clinical.text2': 'Yet today, there is no portable, low-cost wearable that can capture torque and TPT during real movements.',
    'clinical.text3': 'We estimate knee forces from sEMG and IMU signals, representing the first application of this approach to calculate knee torque during vertical jumps for ACL return-to-play assessment (Chen et al., 2017).',
    'clinical.text4': 'We supplement our demo by combining our IMU data with publicly available biomechanics datasets that include sEMG recordings across various dynamic tasks (Scherpereel et al., 2023).',
    // Solution
    'solution.title': 'The Solution',
    'solution.subtitle': 'Knee Torque Tracker',
    'solution.description': 'Low-cost wearable biomechanics system',
    'solution.sensor1.title': '3 sEMG Sensors',
    'solution.sensor1.desc': 'VL, RF, BF muscle groups',
    'solution.sensor2.title': '2 IMUs',
    'solution.sensor2.desc': 'Thigh + shank positioning',
    'solution.sensor3.title': 'Arduino Uno R3',
    'solution.sensor3.desc': 'Microcontroller',
    'solution.price': '< $150',
    'solution.bom': 'Bill of Materials',
    'solution.accessibility': 'Designed to be accessible for schools, community clinics, and youth athletes across the globe',
    // How It Works
    'howitworks.title': 'How It Works',
    'howitworks.step1': 'IMUs & sEMGs',
    'howitworks.step2': 'CSV',
    'howitworks.step3': 'Biomechanical Model',
    'howitworks.step4': 'Report',
    'howitworks.outputs': 'Outputs',
    'howitworks.output1': 'Peak Torque',
    'howitworks.output2': 'Time-to-Peak Torque',
    'howitworks.output3': 'L/R Asymmetry',
    // Dashboard
    'dashboard.title': 'Live Dashboard',
    // Muscle
    'muscle.title': 'Muscle Activation',
    'muscle.curves': 'EMG Activation Curves',
    'muscle.quad': 'Quadriceps Activation',
    'muscle.hamstring': 'Hamstring Activation',
    'muscle.gastro': 'Gastrocnemius Activation',
    'muscle.monitor': 'Monitor muscle co-contraction and activation patterns',
    'muscle.finding': 'Key Finding:',
    'muscle.finding.text': 'Reduced early activation in the hamstrings on the injured side: exactly what PT literature describes in post-ACL patients.',
    // Summary
    'summary.title': 'Recovery Summary',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.problem': 'Problema',
    'nav.clinical': 'Perspectiva Clínica',
    'nav.solution': 'Solución',
    'nav.how-it-works': 'Cómo Funciona',
    'nav.dashboard': 'Datos Cinemáticos',
    'nav.muscle': 'Activación Muscular',
    'nav.summary': 'Panel',
    'home.title': 'Groundwork',
    'home.subtitle': 'Catches equipment failures before they happen. Proves it never left the plant.',
    'problem.title': 'El Problema',
    'problem.text': 'A pentest finds your vulnerabilities... but it costs',
    'problem.cost': '$50,000',
    'problem.stat1.number': '45%',
    'problem.stat1.text': 'Of discovered vulnerabilities remain unpatched after 12 months because fixing them requires manual effort nobody has time for.',
    'problem.stat2.number': '$4.4M',
    'problem.stat2.text': 'Average cost of a data breach in 2025, with vulnerability exploitation remaining one of the leading causes.',
    'problem.stat3.number': '17hrs',
    'problem.stat3.text': 'Per week developers spend on security tasks, much of it translating reports into fixes that could have been automated.',
    'problem.question': 'How do we give every developer, not just enterprises, automated security testing that goes all the way to the fix?',
    'clinical.title': 'Perspectiva Clínica',
    'clinical.text1': 'El Torque Máximo (PT) y el Tiempo al Torque Máximo (TPT) se reconocen como marcadores críticos de la recuperación completa del LCA, especialmente la simetría entre la rodilla lesionada y la sana (Westwood et al., 2025).',
    'clinical.text2': 'Sin embargo, hoy en día no existe un dispositivo portátil de bajo costo que pueda capturar torque y TPT durante movimientos reales.',
    'clinical.text3': 'Estimamos las fuerzas de la rodilla a partir de señales sEMG e IMU, representando la primera aplicación de este enfoque para calcular el torque de la rodilla durante saltos verticales para la evaluación de regreso al juego del LCA (Chen et al., 2017).',
    'clinical.text4': 'Complementamos nuestra demostración combinando nuestros datos IMU con conjuntos de datos de biomecánica disponibles públicamente que incluyen grabaciones sEMG en varias tareas dinámicas (Scherpereel et al., 2023).',
    'solution.title': 'La Solución',
    'solution.subtitle': 'Rastreador de Torque de Rodilla',
    'solution.description': 'Sistema de biomecánica portátil de bajo costo',
    'solution.sensor1.title': '3 Sensores sEMG',
    'solution.sensor1.desc': 'Grupos musculares VL, RF, BF',
    'solution.sensor2.title': '2 IMUs',
    'solution.sensor2.desc': 'Posicionamiento de muslo y pierna',
    'solution.sensor3.title': 'Arduino Uno R3',
    'solution.sensor3.desc': 'Microcontrolador',
    'solution.price': '< $150',
    'solution.bom': 'Lista de Materiales',
    'solution.accessibility': 'Diseñado para ser accesible para escuelas, clínicas comunitarias y atletas juveniles en todo el mundo',
    'howitworks.title': 'Cómo Funciona',
    'howitworks.step1': 'IMUs y sEMGs',
    'howitworks.step2': 'CSV',
    'howitworks.step3': 'Modelo Biomecánico',
    'howitworks.step4': 'Informe',
    'howitworks.outputs': 'Salidas',
    'howitworks.output1': 'Torque Máximo',
    'howitworks.output2': 'Tiempo al Torque Máximo',
    'howitworks.output3': 'Asimetría L/R',
    'dashboard.title': 'Panel en Vivo',
    'muscle.title': 'Activación Muscular',
    'muscle.curves': 'Curvas de Activación EMG',
    'muscle.quad': 'Activación de Cuádriceps',
    'muscle.hamstring': 'Activación de Isquiotibiales',
    'muscle.gastro': 'Activación de Gastrocnemio',
    'muscle.monitor': 'Monitorear la co-contracción muscular y los patrones de activación',
    'muscle.finding': 'Hallazgo Clave:',
    'muscle.finding.text': 'Reducción de la activación temprana en los isquiotibiales del lado lesionado — exactamente lo que describe la literatura de fisioterapia en pacientes post-LCA.',
    'summary.title': 'Resumen de Recuperación',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.problem': 'Problème',
    'nav.clinical': 'Perspective Clinique',
    'nav.solution': 'Solution',
    'nav.how-it-works': 'Comment Ça Marche',
    'nav.dashboard': 'Données Cinématiques',
    'nav.muscle': 'Activation Musculaire',
    'nav.summary': 'Tableau de Bord',
    'home.title': 'Groundwork',
    'home.subtitle': 'Catches equipment failures before they happen. Proves it never left the plant.',
    'problem.title': 'Le Problème',
    'problem.text': 'A pentest finds your vulnerabilities... but it costs',
    'problem.cost': '$50,000',
    'problem.stat1.number': '45%',
    'problem.stat1.text': 'Of discovered vulnerabilities remain unpatched after 12 months because fixing them requires manual effort nobody has time for.',
    'problem.stat2.number': '$4.4M',
    'problem.stat2.text': 'Average cost of a data breach in 2025, with vulnerability exploitation remaining one of the leading causes.',
    'problem.stat3.number': '17hrs',
    'problem.stat3.text': 'Per week developers spend on security tasks, much of it translating reports into fixes that could have been automated.',
    'problem.question': 'How do we give every developer, not just enterprises, automated security testing that goes all the way to the fix?',
    'clinical.title': 'Perspective Clinique',
    'clinical.text1': 'Le Couple de Pointe (PT) et le Temps jusqu\'au Couple de Pointe (TPT) sont reconnus comme des marqueurs critiques de la récupération complète du LCA, en particulier la symétrie entre le genou blessé et le genou sain (Westwood et al., 2025).',
    'clinical.text2': 'Pourtant, aujourd\'hui, il n\'existe aucun dispositif portable et peu coûteux qui puisse capturer le couple et le TPT pendant les mouvements réels.',
    'clinical.text3': 'Nous estimons les forces du genou à partir des signaux sEMG et IMU, représentant la première application de cette approche pour calculer le couple du genou lors de sauts verticaux pour l\'évaluation du retour au jeu du LCA (Chen et al., 2017).',
    'clinical.text4': 'Nous complétons notre démo en combinant nos données IMU avec des ensembles de données de biomécanique disponibles publiquement qui incluent des enregistrements sEMG sur diverses tâches dynamiques (Scherpereel et al., 2023).',
    'solution.title': 'La Solution',
    'solution.subtitle': 'Suivi du Couple du Genou',
    'solution.description': 'Système de biomécanique portable à faible coût',
    'solution.sensor1.title': '3 Capteurs sEMG',
    'solution.sensor1.desc': 'Groupes musculaires VL, RF, BF',
    'solution.sensor2.title': '2 IMUs',
    'solution.sensor2.desc': 'Positionnement cuisse et jambe',
    'solution.sensor3.title': 'Arduino Uno R3',
    'solution.sensor3.desc': 'Microcontrôleur',
    'solution.price': '< 150 $',
    'solution.bom': 'Liste des Matériaux',
    'solution.accessibility': 'Conçu pour être accessible aux écoles, cliniques communautaires et athlètes jeunes du monde entier',
    'howitworks.title': 'Comment Ça Marche',
    'howitworks.step1': 'IMUs et sEMGs',
    'howitworks.step2': 'CSV',
    'howitworks.step3': 'Modèle Biomécanique',
    'howitworks.step4': 'Rapport',
    'howitworks.outputs': 'Sorties',
    'howitworks.output1': 'Couple de Pointe',
    'howitworks.output2': 'Temps jusqu\'au Couple de Pointe',
    'howitworks.output3': 'Asymétrie G/D',
    'dashboard.title': 'Tableau de Bord en Direct',
    'muscle.title': 'Activation Musculaire',
    'muscle.curves': 'Courbes d\'Activation EMG',
    'muscle.quad': 'Activation des Quadriceps',
    'muscle.hamstring': 'Activation des Ischio-jambiers',
    'muscle.gastro': 'Activation du Gastrocnémien',
    'muscle.monitor': 'Surveiller la co-contraction musculaire et les modèles d\'activation',
    'muscle.finding': 'Découverte Clé:',
    'muscle.finding.text': 'Réduction de l\'activation précoce dans les ischio-jambiers du côté blessé — exactement ce que décrit la littérature de physiothérapie chez les patients post-LCA.',
    'summary.title': 'Résumé de Récupération',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.problem': 'Problem',
    'nav.clinical': 'Klinische Einsicht',
    'nav.solution': 'Lösung',
    'nav.how-it-works': 'Wie Es Funktioniert',
    'nav.dashboard': 'Kinematische Daten',
    'nav.muscle': 'Muskelaktivierung',
    'nav.summary': 'Dashboard',
    'home.title': 'Groundwork',
    'home.subtitle': 'Catches equipment failures before they happen. Proves it never left the plant.',
    'problem.title': 'Das Problem',
    'problem.text': 'A pentest finds your vulnerabilities... but it costs',
    'problem.cost': '$50,000',
    'problem.stat1.number': '45%',
    'problem.stat1.text': 'Of discovered vulnerabilities remain unpatched after 12 months because fixing them requires manual effort nobody has time for.',
    'problem.stat2.number': '$4.4M',
    'problem.stat2.text': 'Average cost of a data breach in 2025, with vulnerability exploitation remaining one of the leading causes.',
    'problem.stat3.number': '17hrs',
    'problem.stat3.text': 'Per week developers spend on security tasks, much of it translating reports into fixes that could have been automated.',
    'problem.question': 'How do we give every developer, not just enterprises, automated security testing that goes all the way to the fix?',
    'clinical.title': 'Klinische Einsicht',
    'clinical.text1': 'Spitzendrehmoment (PT) und Zeit bis zum Spitzendrehmoment (TPT) werden jetzt als kritische neuromuskuläre Marker für die vollständige ACL-Erholung anerkannt, insbesondere die Symmetrie zwischen dem verletzten und gesunden Knie (Westwood et al., 2025).',
    'clinical.text2': 'Doch heute gibt es kein tragbares, kostengünstiges Wearable, das Drehmoment und TPT während echter Bewegungen erfassen kann.',
    'clinical.text3': 'Wir schätzen Kniekräfte aus sEMG- und IMU-Signalen ab und repräsentieren die erste Anwendung dieses Ansatzes zur Berechnung des Kniedrehmoments bei vertikalen Sprüngen für die ACL-Return-to-Play-Bewertung (Chen et al., 2017).',
    'clinical.text4': 'Wir ergänzen unsere Demo, indem wir unsere IMU-Daten mit öffentlich verfügbaren Biomechanik-Datensätzen kombinieren, die sEMG-Aufzeichnungen über verschiedene dynamische Aufgaben hinweg enthalten (Scherpereel et al., 2023).',
    'solution.title': 'Die Lösung',
    'solution.subtitle': 'Knie-Drehmoment-Tracker',
    'solution.description': 'Kostengünstiges tragbares Biomechanik-System',
    'solution.sensor1.title': '3 sEMG-Sensoren',
    'solution.sensor1.desc': 'Muskelgruppen VL, RF, BF',
    'solution.sensor2.title': '2 IMUs',
    'solution.sensor2.desc': 'Oberschenkel- und Schienbein-Positionierung',
    'solution.sensor3.title': 'Arduino Uno R3',
    'solution.sensor3.desc': 'Mikrocontroller',
    'solution.price': '< 150 $',
    'solution.bom': 'Stückliste',
    'solution.accessibility': 'Entworfen, um für Schulen, Gemeinschaftskliniken und Jugendsportler weltweit zugänglich zu sein',
    'howitworks.title': 'Wie Es Funktioniert',
    'howitworks.step1': 'IMUs & sEMGs',
    'howitworks.step2': 'CSV',
    'howitworks.step3': 'Biomechanisches Modell',
    'howitworks.step4': 'Bericht',
    'howitworks.outputs': 'Ausgaben',
    'howitworks.output1': 'Spitzendrehmoment',
    'howitworks.output2': 'Zeit bis zum Spitzendrehmoment',
    'howitworks.output3': 'L/R-Asymmetrie',
    'dashboard.title': 'Live-Dashboard',
    'muscle.title': 'Muskelaktivierung',
    'muscle.curves': 'EMG-Aktivierungskurven',
    'muscle.quad': 'Quadrizeps-Aktivierung',
    'muscle.hamstring': 'Hamstring-Aktivierung',
    'muscle.gastro': 'Gastrocnemius-Aktivierung',
    'muscle.monitor': 'Überwachen Sie die Muskelko-Kontraktion und Aktivierungsmuster',
    'muscle.finding': 'Wichtiger Befund:',
    'muscle.finding.text': 'Reduzierte frühe Aktivierung in den Hamstrings auf der verletzten Seite — genau das, was die PT-Literatur bei post-ACL-Patienten beschreibt.',
    'summary.title': 'Erholungszusammenfassung',
  },
  zh: {
    'nav.home': '首页',
    'nav.problem': '问题',
    'nav.clinical': '临床见解',
    'nav.solution': '解决方案',
    'nav.how-it-works': '工作原理',
    'nav.dashboard': '运动学数据',
    'nav.muscle': '肌肉激活',
    'nav.summary': '仪表板',
    'home.title': 'Groundwork',
    'home.subtitle': 'Catches equipment failures before they happen. Proves it never left the plant.',
    'problem.title': '问题',
    'problem.text': 'A pentest finds your vulnerabilities... but it costs',
    'problem.cost': '$50,000',
    'problem.stat1.number': '45%',
    'problem.stat1.text': 'Of discovered vulnerabilities remain unpatched after 12 months because fixing them requires manual effort nobody has time for.',
    'problem.stat2.number': '$4.4M',
    'problem.stat2.text': 'Average cost of a data breach in 2025, with vulnerability exploitation remaining one of the leading causes.',
    'problem.stat3.number': '17hrs',
    'problem.stat3.text': 'Per week developers spend on security tasks, much of it translating reports into fixes that could have been automated.',
    'problem.question': 'How do we give every developer, not just enterprises, automated security testing that goes all the way to the fix?',
    'clinical.title': '临床见解',
    'clinical.text1': '峰值扭矩（PT）和达到峰值扭矩的时间（TPT）现在被认为是完全ACL恢复的关键神经肌肉标志，特别是受伤和健康膝盖之间的对称性（Westwood等人，2025年）。',
    'clinical.text2': '然而，目前还没有便携式、低成本的穿戴设备可以在真实运动过程中捕获扭矩和TPT。',
    'clinical.text3': '我们从sEMG和IMU信号估计膝关节力，这是首次应用这种方法计算垂直跳跃期间的膝关节扭矩，用于ACL回归比赛评估（Chen等人，2017年）。',
    'clinical.text4': '我们通过将IMU数据与公开可用的生物力学数据集相结合来补充我们的演示，这些数据集包括各种动态任务中的sEMG记录（Scherpereel等人，2023年）。',
    'solution.title': '解决方案',
    'solution.subtitle': '膝关节扭矩追踪器',
    'solution.description': '低成本可穿戴生物力学系统',
    'solution.sensor1.title': '3个sEMG传感器',
    'solution.sensor1.desc': 'VL、RF、BF肌群',
    'solution.sensor2.title': '2个IMU',
    'solution.sensor2.desc': '大腿和小腿定位',
    'solution.sensor3.title': 'Arduino Uno R3',
    'solution.sensor3.desc': '微控制器',
    'solution.price': '< $150',
    'solution.bom': '物料清单',
    'solution.accessibility': '设计为全球学校、社区诊所和青年运动员提供便利',
    'howitworks.title': '工作原理',
    'howitworks.step1': 'IMU和sEMG',
    'howitworks.step2': 'CSV',
    'howitworks.step3': '生物力学模型',
    'howitworks.step4': '报告',
    'howitworks.outputs': '输出',
    'howitworks.output1': '峰值扭矩',
    'howitworks.output2': '达到峰值扭矩的时间',
    'howitworks.output3': '左右不对称',
    'dashboard.title': '实时仪表板',
    'muscle.title': '肌肉激活',
    'muscle.curves': 'EMG激活曲线',
    'muscle.quad': '股四头肌激活',
    'muscle.hamstring': '腘绳肌激活',
    'muscle.gastro': '腓肠肌激活',
    'muscle.monitor': '监测肌肉共同收缩和激活模式',
    'muscle.finding': '关键发现：',
    'muscle.finding.text': '受伤侧腘绳肌早期激活减少——这正是物理治疗文献在ACL术后患者中描述的。',
    'summary.title': '恢复总结',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.problem': '問題',
    'nav.clinical': '臨床的洞察',
    'nav.solution': '解決策',
    'nav.how-it-works': '仕組み',
    'nav.dashboard': '運動学データ',
    'nav.muscle': '筋活動',
    'nav.summary': 'ダッシュボード',
    'home.title': 'Groundwork',
    'home.subtitle': 'Catches equipment failures before they happen. Proves it never left the plant.',
    'problem.title': '問題',
    'problem.text': 'A pentest finds your vulnerabilities... but it costs',
    'problem.cost': '$50,000',
    'problem.stat1.number': '45%',
    'problem.stat1.text': 'Of discovered vulnerabilities remain unpatched after 12 months because fixing them requires manual effort nobody has time for.',
    'problem.stat2.number': '$4.4M',
    'problem.stat2.text': 'Average cost of a data breach in 2025, with vulnerability exploitation remaining one of the leading causes.',
    'problem.stat3.number': '17hrs',
    'problem.stat3.text': 'Per week developers spend on security tasks, much of it translating reports into fixes that could have been automated.',
    'problem.question': 'How do we give every developer, not just enterprises, automated security testing that goes all the way to the fix?',
    'clinical.title': '臨床的洞察',
    'clinical.text1': 'ピークトルク（PT）とピークトルク到達時間（TPT）は、完全なACL回復の重要な神経筋マーカーとして認識されており、特に負傷した膝と健康な膝の間の対称性が重要です（Westwood et al., 2025）。',
    'clinical.text2': 'しかし、今日、実際の動き中にトルクとTPTを捕捉できる携帯型の低コストウェアラブルは存在しません。',
    'clinical.text3': 'sEMGおよびIMU信号から膝の力を推定し、ACL復帰プレー評価のための垂直ジャンプ中の膝トルクを計算するこのアプローチの最初の応用を表しています（Chen et al., 2017）。',
    'clinical.text4': '公開されている生体力学データセットとIMUデータを組み合わせてデモを補完します。これらのデータセットには、さまざまな動的タスクにわたるsEMG記録が含まれています（Scherpereel et al., 2023）。',
    'solution.title': '解決策',
    'solution.subtitle': '膝トルクトラッカー',
    'solution.description': '低コストウェアラブル生体力学システム',
    'solution.sensor1.title': '3つのsEMGセンサー',
    'solution.sensor1.desc': 'VL、RF、BF筋群',
    'solution.sensor2.title': '2つのIMU',
    'solution.sensor2.desc': '大腿部と下腿部の位置測定',
    'solution.sensor3.title': 'Arduino Uno R3',
    'solution.sensor3.desc': 'マイクロコントローラー',
    'solution.price': '< $150',
    'solution.bom': '部品リスト',
    'solution.accessibility': '世界中の学校、コミュニティクリニック、若手アスリートが利用できるように設計されています',
    'howitworks.title': '仕組み',
    'howitworks.step1': 'IMUとsEMG',
    'howitworks.step2': 'CSV',
    'howitworks.step3': '生体力学モデル',
    'howitworks.step4': 'レポート',
    'howitworks.outputs': '出力',
    'howitworks.output1': 'ピークトルク',
    'howitworks.output2': 'ピークトルク到達時間',
    'howitworks.output3': '左右非対称',
    'dashboard.title': 'ライブダッシュボード',
    'muscle.title': '筋活動',
    'muscle.curves': 'EMG活動曲線',
    'muscle.quad': '大腿四頭筋活動',
    'muscle.hamstring': 'ハムストリング活動',
    'muscle.gastro': '腓腹筋活動',
    'muscle.monitor': '筋の共同収縮と活動パターンを監視',
    'muscle.finding': '重要な発見：',
    'muscle.finding.text': '負傷側のハムストリングでの早期活動の減少—これは、ACL術後患者において理学療法文献が説明していることと正確に一致しています。',
    'summary.title': '回復サマリー',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
